//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kwd.Rdf.Std.DublinCore {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Terms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Terms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kwd.Rdf.Std.DublinCore.Terms", typeof(Terms).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/abstract.
        /// </summary>
        public static string Abstract {
            get {
                return ResourceManager.GetString("Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/accessRights.
        /// </summary>
        public static string AccessRights {
            get {
                return ResourceManager.GetString("AccessRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/accrualMethod.
        /// </summary>
        public static string AccrualMethod {
            get {
                return ResourceManager.GetString("AccrualMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/accrualPeriodicity.
        /// </summary>
        public static string AccrualPeriodicity {
            get {
                return ResourceManager.GetString("AccrualPeriodicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/accrualPolicy.
        /// </summary>
        public static string AccrualPolicy {
            get {
                return ResourceManager.GetString("AccrualPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/alternative.
        /// </summary>
        public static string AlternativeTitle {
            get {
                return ResourceManager.GetString("AlternativeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/audience.
        /// </summary>
        public static string Audience {
            get {
                return ResourceManager.GetString("Audience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/educationLevel.
        /// </summary>
        public static string AudienceEducationLevel {
            get {
                return ResourceManager.GetString("AudienceEducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/bibliographicCitation.
        /// </summary>
        public static string Bibliographic_Citation {
            get {
                return ResourceManager.GetString("Bibliographic Citation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/conformsTo.
        /// </summary>
        public static string ConformsTo {
            get {
                return ResourceManager.GetString("ConformsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/contributor.
        /// </summary>
        public static string Contributor {
            get {
                return ResourceManager.GetString("Contributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/coverage.
        /// </summary>
        public static string Coverage {
            get {
                return ResourceManager.GetString("Coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/creator.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/dateAccepted.
        /// </summary>
        public static string DateAccepted {
            get {
                return ResourceManager.GetString("DateAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/available.
        /// </summary>
        public static string DateAvailable {
            get {
                return ResourceManager.GetString("DateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/dateCopyrighted.
        /// </summary>
        public static string DateCopyrighted {
            get {
                return ResourceManager.GetString("DateCopyrighted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/created.
        /// </summary>
        public static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/issued.
        /// </summary>
        public static string DateIssued {
            get {
                return ResourceManager.GetString("DateIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/modified.
        /// </summary>
        public static string DateModified {
            get {
                return ResourceManager.GetString("DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/dateSubmitted.
        /// </summary>
        public static string DateSubmitted {
            get {
                return ResourceManager.GetString("DateSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/valid.
        /// </summary>
        public static string DateValid {
            get {
                return ResourceManager.GetString("DateValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/extent.
        /// </summary>
        public static string Extent {
            get {
                return ResourceManager.GetString("Extent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/hasFormat.
        /// </summary>
        public static string HasFormat {
            get {
                return ResourceManager.GetString("HasFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/hasPart.
        /// </summary>
        public static string HasPart {
            get {
                return ResourceManager.GetString("HasPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/hasVersion.
        /// </summary>
        public static string HasVersion {
            get {
                return ResourceManager.GetString("HasVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/identifier.
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/instructionalMethod.
        /// </summary>
        public static string InstructionalMethod {
            get {
                return ResourceManager.GetString("InstructionalMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/isFormatOf.
        /// </summary>
        public static string IsFormatOf {
            get {
                return ResourceManager.GetString("IsFormatOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/isPartOf.
        /// </summary>
        public static string IsPartOf {
            get {
                return ResourceManager.GetString("IsPartOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/isReferencedBy.
        /// </summary>
        public static string IsReferencedBy {
            get {
                return ResourceManager.GetString("IsReferencedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/isReplacedBy.
        /// </summary>
        public static string IsReplacedBy {
            get {
                return ResourceManager.GetString("IsReplacedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/isRequiredBy.
        /// </summary>
        public static string IsRequiredBy {
            get {
                return ResourceManager.GetString("IsRequiredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/isVersionOf.
        /// </summary>
        public static string IsVersionOf {
            get {
                return ResourceManager.GetString("IsVersionOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/license.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/mediator.
        /// </summary>
        public static string Mediator {
            get {
                return ResourceManager.GetString("Mediator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/provenance.
        /// </summary>
        public static string Provenance {
            get {
                return ResourceManager.GetString("Provenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/references.
        /// </summary>
        public static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/relation.
        /// </summary>
        public static string Relation {
            get {
                return ResourceManager.GetString("Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/replaces.
        /// </summary>
        public static string Replaces {
            get {
                return ResourceManager.GetString("Replaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/requires.
        /// </summary>
        public static string Requires {
            get {
                return ResourceManager.GetString("Requires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/rights.
        /// </summary>
        public static string Rights {
            get {
                return ResourceManager.GetString("Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/rightsHolder.
        /// </summary>
        public static string RightsHolder {
            get {
                return ResourceManager.GetString("RightsHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/spatial.
        /// </summary>
        public static string SpatialCoverage {
            get {
                return ResourceManager.GetString("SpatialCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/tableOfContents.
        /// </summary>
        public static string TableOfContents {
            get {
                return ResourceManager.GetString("TableOfContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/temporal.
        /// </summary>
        public static string TemporalCoverage {
            get {
                return ResourceManager.GetString("TemporalCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/terms/type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
